### ISSUE TITLE
Configure "odd" SSH bastion hostname for Più

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/stups-cli-support#1]
"stups configure" should also set the "odd" SSH bastion hostname for Più (it's AWS account dependent).

**Comment by whiskeysierra** [comment]
> it's AWS account dependent

And region!

I use the [following](https://github.com/whiskeysierra/dotfiles/blob/master/plugins/stups/piu.zsh):

```
alias piu='ODD_HOST="odd-$AWS_DEFAULT_REGION.$(account).zalan.do" USER=$PIU_USER piu $*'
```

`account` is defined as [this](https://github.com/whiskeysierra/dotfiles/blob/master/plugins/stups/mai.zsh#L9):

```
cat ~/.config/mai/last_update.yaml | sed -E 's/.*profile: *([^,}]+).*/\1/'
```

**Comment by whiskeysierra** [comment]
The last part only works if you use the account names as mai profile names.

**Comment by hjacobs** [comment]
This is no longer necessary as the STUPS tooling has reached end of life.
